version: '3.7'
services:
  gateway:
    image: ghcr.io/4sitive/gateway:latest
    restart: always
    container_name: gateway
    hostname: gateway
    network_mode: bridge
    environment:
      JAVA_OPTS: >-
        -Dfile.encoding=UTF-8
        -Dcrypto.policy=unlimited
        -Dsun.net.inetaddr.ttl=0
        -Dsun.net.inetaddr.negative.ttl=0
        -Djava.net.preferIPv4Stack=true
        -Djava.security.egd=file:/dev/./urandom
        -Duser.country=KR
        -Duser.language=ko
        -Duser.timezone=Asia/Seoul
      SPRING_PROFILES_ACTIVE: LOGING_FILE,LOGGING_CONSOLE_JSON
      LOG_PATH: /workspace/log
      SERVER_PORT: 8080
      MANAGEMENT_SERVER_PORT: 8081
      SERVER_SSL_KEYSTORE: classpath:keystore.pfx
      SERVER_SSL_KEYSTOREPASSWORD: $KEYSTORE_PASSWORD
    ports:
      - "8080:8080"
      - "8081:8081"