name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw -B spring-boot:build-image --file pom.xml -Dspring-boot.build-image.imageName=ghcr.io/4sitive/gateway
  deploy:
    needs: build
    runs-on: [ self-hosted ]
    steps:
      - name: Deploy with Docker
        env:
          SERVER_SSL_KEYSTORE: classpath:keystore.pfx
          SERVER_SSL_KEYSTOREPASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        run: |
          docker-compose up --no-deps --build --force-recreate --detach
